var searchData=
[
  ['de_20código_20c_0',['Estilo de código C++.',['../md_style.html#autotoc_md288',1,'']]],
  ['de_20colisión_203d_1',['Archivo de descripción de volumen de colisión 3D.',['../_pre_built_collider3_d_file.html',1,'jsonfiles']]],
  ['de_20contenido_2',['&lt;em&gt;&lt;b&gt;Nuevo&lt;/b&gt;&lt;/em&gt; Perfiles de contenido',['../md__version_history.html#autotoc_md232',1,'']]],
  ['de_20culling_3',['de culling',['../_material_file_v0.html#cullingV0',1,'Modo de culling.'],['../_material_file_v1.html#cullingV1',1,'Modo de culling.']]],
  ['de_20depth_20testing_4',['de depth testing',['../_material_file_v0.html#depthtestingV0',1,'Modo de depth testing.'],['../_material_file_v1.html#depthtestingV1',1,'Modo de depth testing.']]],
  ['de_20descripción_20de_20mapa_20cúbico_5',['Archivo de descripción de mapa cúbico.',['../_cubemap_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20material_6',['Archivo de descripción de material.',['../_material_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20material_20revisión_200_7',['Archivo de descripción de material (revisión 0).',['../_material_file_v0.html',1,'MaterialFile']]],
  ['de_20descripción_20de_20material_20revisión_201_8',['Archivo de descripción de material (revisión 1).',['../_material_file_v1.html',1,'MaterialFile']]],
  ['de_20descripción_20de_20modelos_203d_9',['Archivo de descripción de modelos 3D.',['../_model3_d_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20recursos_10',['Archivos de descripción de recursos.',['../jsonfiles.html',1,'']]],
  ['de_20descripción_20de_20un_20mapa_20de_20iluminación_20especular_11',['Archivo de descripción de un mapa de iluminación especular.',['../_specular_map_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20un_20mapa_20de_20irradiancia_12',['Archivo de descripción de un mapa de irradiancia.',['../_irradiance_map_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20una_20fuente_20de_20texto_13',['Archivo de descripción de una fuente de texto.',['../_font_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20una_20textura_202d_14',['Archivo de descripción de una textura 2D.',['../_texture_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20volumen_20de_20colisión_203d_15',['Archivo de descripción de volumen de colisión 3D.',['../_pre_built_collider3_d_file.html',1,'jsonfiles']]],
  ['de_20encabezado_16',['Archivos de encabezado',['../md_style.html#autotoc_md290',1,'']]],
  ['de_20iluminación_20especular_17',['Archivo de descripción de un mapa de iluminación especular.',['../_specular_map_file.html',1,'jsonfiles']]],
  ['de_20irradiancia_18',['Archivo de descripción de un mapa de irradiancia.',['../_irradiance_map_file.html',1,'jsonfiles']]],
  ['de_20mapa_20cúbico_19',['Archivo de descripción de mapa cúbico.',['../_cubemap_file.html',1,'jsonfiles']]],
  ['de_20material_20',['de material',['../_material_file.html',1,'Archivo de descripción de  material.'],['../_material_file_v0.html#materialtypeV0',1,'Tipos de material.'],['../_material_file_v1.html#materialtypeV1',1,'Tipos de material.']]],
  ['de_20material_20revisión_200_21',['Archivo de descripción de material (revisión 0).',['../_material_file_v0.html',1,'MaterialFile']]],
  ['de_20material_20revisión_201_22',['Archivo de descripción de material (revisión 1).',['../_material_file_v1.html',1,'MaterialFile']]],
  ['de_20modelos_203d_23',['Archivo de descripción de modelos 3D.',['../_model3_d_file.html',1,'jsonfiles']]],
  ['de_20polígonos_24',['de polígonos',['../_material_file_v0.html#polygonmodeV0',1,'Modo de renderizado de polígonos.'],['../_material_file_v1.html#polygonmodeV1',1,'Modo de renderizado de polígonos.']]],
  ['de_20recursos_25',['Archivos de descripción de recursos.',['../jsonfiles.html',1,'']]],
  ['de_20renderizado_20de_20polígonos_26',['de renderizado de polígonos',['../_material_file_v0.html#polygonmodeV0',1,'Modo de renderizado de polígonos.'],['../_material_file_v1.html#polygonmodeV1',1,'Modo de renderizado de polígonos.']]],
  ['de_20texto_27',['Archivo de descripción de una fuente de texto.',['../_font_file.html',1,'jsonfiles']]],
  ['de_20un_20mapa_20de_20iluminación_20especular_28',['Archivo de descripción de un mapa de iluminación especular.',['../_specular_map_file.html',1,'jsonfiles']]],
  ['de_20un_20mapa_20de_20irradiancia_29',['Archivo de descripción de un mapa de irradiancia.',['../_irradiance_map_file.html',1,'jsonfiles']]],
  ['de_20una_20fuente_20de_20texto_30',['Archivo de descripción de una fuente de texto.',['../_font_file.html',1,'jsonfiles']]],
  ['de_20una_20textura_202d_31',['Archivo de descripción de una textura 2D.',['../_texture_file.html',1,'jsonfiles']]],
  ['de_20versiones_32',['Historial de versiones.',['../md__version_history.html#autotoc_md0',1,'']]],
  ['de_20volumen_20de_20colisión_203d_33',['Archivo de descripción de volumen de colisión 3D.',['../_pre_built_collider3_d_file.html',1,'jsonfiles']]],
  ['depth_20testing_34',['depth testing',['../_material_file_v0.html#depthtestingV0',1,'Modo de depth testing.'],['../_material_file_v1.html#depthtestingV1',1,'Modo de depth testing.']]],
  ['descripción_20de_20mapa_20cúbico_35',['Archivo de descripción de mapa cúbico.',['../_cubemap_file.html',1,'jsonfiles']]],
  ['descripción_20de_20material_36',['Archivo de descripción de material.',['../_material_file.html',1,'jsonfiles']]],
  ['descripción_20de_20material_20revisión_200_37',['Archivo de descripción de material (revisión 0).',['../_material_file_v0.html',1,'MaterialFile']]],
  ['descripción_20de_20material_20revisión_201_38',['Archivo de descripción de material (revisión 1).',['../_material_file_v1.html',1,'MaterialFile']]],
  ['descripción_20de_20modelos_203d_39',['Archivo de descripción de modelos 3D.',['../_model3_d_file.html',1,'jsonfiles']]],
  ['descripción_20de_20recursos_40',['Archivos de descripción de recursos.',['../jsonfiles.html',1,'']]],
  ['descripción_20de_20un_20mapa_20de_20iluminación_20especular_41',['Archivo de descripción de un mapa de iluminación especular.',['../_specular_map_file.html',1,'jsonfiles']]],
  ['descripción_20de_20un_20mapa_20de_20irradiancia_42',['Archivo de descripción de un mapa de irradiancia.',['../_irradiance_map_file.html',1,'jsonfiles']]],
  ['descripción_20de_20una_20fuente_20de_20texto_43',['Archivo de descripción de una fuente de texto.',['../_font_file.html',1,'jsonfiles']]],
  ['descripción_20de_20una_20textura_202d_44',['Archivo de descripción de una textura 2D.',['../_texture_file.html',1,'jsonfiles']]],
  ['descripción_20de_20volumen_20de_20colisión_203d_45',['Archivo de descripción de volumen de colisión 3D.',['../_pre_built_collider3_d_file.html',1,'jsonfiles']]],
  ['design_46',['Design',['../md_ecs_01messaging.html#autotoc_md304',1,'']]],
  ['design_20philosophy_20implementation_47',['Design philosophy &amp;amp; implementation',['../md_philosophy.html',1,'']]],
  ['details_48',['Implementation details',['../md_ecs_01messaging.html#autotoc_md305',1,'']]]
];
